version: '3'
services:
  monsaloninline-app:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=monsalonline
      - MYSQL_ROOT_PASSWORD=123@Password
    volumes:
      - db-data:/var/lib/mysql
      # - ./DB:/Home
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8080:80
volumes:
  db-data: